site_name: ASOF
site_description: Documentação do Projeto ASOF
site_author: Time ASOF
repo_url: https://github.com/seu-usuario/ASOF

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

nav:
  - Início: index.md
  - Guia do Usuário:
    - Introdução: user-guide/introduction.md
    - Primeiros Passos: user-guide/getting-started.md
    - Funcionalidades: user-guide/features.md
  - Guia do Desenvolvedor:
    - Configuração: dev-guide/setup.md
    - Estrutura do Projeto: dev-guide/project-structure.md
    - Fluxo de Trabalho: dev-guide/workflow.md
    - Testes: dev-guide/testing.md
    - Solução de Problemas: dev-guide/troubleshooting.md
  - API:
    - Visão Geral: api/overview.md
    - Endpoints: api/endpoints.md
  - Sobre:
    - Changelog: about/changelog.md
    - Contribuindo: about/contributing.md
    - Licença: about/license.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

plugins:
  - search:
      lang: pt
  - minify:
      minify_html: true 